### PR TITLE
Add simple graphics API for lua

### PR DESCRIPTION
**Pull request by mariobadr**
An API for loading and drawing textures has been added, as well as the ability to clear the screen to create simple animations.

### CODE REVIEW

**Comment by chutchinson** [comment]
Before I merge this, I would like to see the following changes:
- Use enum singleton pattern (http://stackoverflow.com/questions/70689/what-is-an-efficient-way-to-implement-a-singleton-pattern-in-java)
- Remove sample lua program from src/main/resources or preferrably create a unit test and move the sample program to src/test/resources. I feel we should keep these samples in the demos project where the C++ samples are. Samples for unit testing are of course perfectly fine.

**Comment by mariobadr** [comment]
Which singleton are you referring to? The Game singleton is an enum singleton pattern, and that should be the only singleton I created if I recall correctly.

**Comment by chutchinson** [comment]
I'm sorry, I made a mistake with the singleton comment. I saw the INSTANCE field and assumed you implemented the typical approach (static final member), and didn't bother to check the code. 

I wanted to point out we can lift the state checking in GameState.java to wherever the engine loop is, to avoid calling the function several times per frame.

**Comment by mariobadr** [comment]
Sorry, confused again: which state checking are you referring to? GameState is just an interface.

**Comment by chutchinson** [comment]
Oh, and I would consider replacing GDX logging with the Java logging API. We can choose a better logging implementation (e.g. log4j, logback, etc) later if we want to without changing any code.

http://www.vogella.com/tutorials/Logging/article.html

**Comment by chutchinson** [comment]
Oops. I mean Game.java in engine-core.

**Comment by mariobadr** [comment]
Are you referring to the multiple instances of gameStates.empty()? There may be times when a function like update() must be called even when gameStates.empty() == true (e.g. continue loading assets). 

The branch should also generally resolve to true (except during initialization), so any processor made in the last 15 (more?) years should be able to speculate correctly and not take the branch penalty hit. The performance hit should be negligible and it avoids exposing the gameStates stack to outside the class (improves encapsulation).

**Comment by chutchinson** [comment]
As far as I know branch prediction only applies to sequential code blocks per logical core; so any other branches in between any of those calls can reduce the prediction accuracy. _(I'm wrong about this too, going for a losing streak tonight)._

I think I agree, though. Regardless, it might be premature to be making that kind of optimization at this stage; game engines need to be fast but there's such a thing as fast enough.

**Comment by mariobadr** [comment]
You are correct. A lot of research has gone into branch prediction, however, and modern day predictors are capable of very high accuracy rates. I'm doing my PhD in computer architecture so if you want to learn more just let me know! :)

**Comment by mariobadr** [comment]
As requested, main.lua has been removed from the repository. I will merge now and work on changing the logging system in a separate branch.

**Pull request merged**
